# Generated by Django 5.2.12 on 2026-03-24 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Начало слота')),
                ('end_at', models.DateTimeField(verbose_name='Конец слота')),
                ('type_slot', models.CharField(choices=[('foot', 'Пеший'), ('bike', 'Велосипед'), ('moped', 'Мопед'), ('car', 'Машина')], default='standard', max_length=20, verbose_name='Тип слота')),
                ('status', models.CharField(choices=[('in_work', 'в работе'), ('offered', 'предложен'), ('planned', 'запланирован'), ('no_show', 'невыход'), ('completed', 'завершён')], db_index=True, default='planned', max_length=20, verbose_name='Статус слота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('courier', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'courier'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slots', to=settings.AUTH_USER_MODEL, verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Таблица слотов',
                'verbose_name_plural': 'Таблица слотов',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_a', models.CharField(max_length=255, verbose_name='Адрес откуда')),
                ('point_b', models.CharField(max_length=255, verbose_name='Адрес куда')),
                ('pickup_lat', models.FloatField(blank=True, null=True, verbose_name='Широта точки забора')),
                ('pickup_lon', models.FloatField(blank=True, null=True, verbose_name='Долгота точки забора')),
                ('dropoff_lat', models.FloatField(blank=True, null=True, verbose_name='Широта точки доставки')),
                ('dropoff_lon', models.FloatField(blank=True, null=True, verbose_name='Долгота точки доставки')),
                ('delivery_status', models.CharField(choices=[('searching_courier', 'Поиск курьера'), ('courier_assigned', 'Курьер назначен'), ('courier_arrived', 'Курьер прибыл'), ('picked_up', 'Забрал посылку'), ('in_delivery', 'В пути'), ('delivered', 'Доставлено'), ('canceled', 'Отменено'), ('courier_arrived_b', 'Курьер прибыл в точку назначения'), ('waiting_pickup', 'Бесплатное ожидание')], default='pending', max_length=50, verbose_name='Статус доставки')),
                ('type_delivery', models.CharField(choices=[('express', 'Экспресс'), ('standard', 'Стандарт')], default='standard', max_length=50, verbose_name='Тип доставки')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('free_waiting_started_at', models.DateTimeField(blank=True, null=True)),
                ('free_waiting_minutes', models.PositiveIntegerField(default=10)),
                ('paid_waiting_started_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_at', models.DateTimeField(blank=True, null=True, verbose_name='Время забора')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Время доставки')),
                ('time_left', models.IntegerField(default=0, verbose_name='Осталось времени')),
                ('deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставить до')),
                ('door_to_door', models.BooleanField(default=False, verbose_name='Доставка от двери до двери')),
                ('sender_name', models.CharField(blank=True, max_length=100, verbose_name='Имя отправителя')),
                ('sender_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон отправителя')),
                ('recipient_name', models.CharField(blank=True, max_length=100, verbose_name='Имя получателя')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон получателя')),
                ('pickup_entrance', models.CharField(blank=True, max_length=20, verbose_name='Подъезд откуда')),
                ('pickup_floor', models.CharField(blank=True, max_length=20, verbose_name='Этаж откуда')),
                ('pickup_apartment', models.CharField(blank=True, max_length=50, verbose_name='Квартира/офис откуда')),
                ('pickup_intercom', models.CharField(blank=True, max_length=50, verbose_name='Домофон откуда')),
                ('pickup_comment', models.TextField(blank=True, default='', verbose_name='Комментарий откуда')),
                ('dropoff_entrance', models.CharField(blank=True, max_length=20, verbose_name='Подъезд куда')),
                ('dropoff_floor', models.CharField(blank=True, max_length=20, verbose_name='Этаж куда')),
                ('dropoff_apartment', models.CharField(blank=True, max_length=50, verbose_name='Квартира/офис куда')),
                ('dropoff_intercom', models.CharField(blank=True, max_length=50, verbose_name='Домофон куда')),
                ('dropoff_comment', models.TextField(blank=True, default='', verbose_name='Комментарий куда')),
                ('client_comment', models.TextField(blank=True, default='', verbose_name='Комментарий клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'client'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('courier', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'courier'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Курьер')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.courierslot', verbose_name='Слот')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принят'), ('rejected', 'Отклонен'), ('expired', 'Истек')], db_index=True, default='pending', max_length=20, verbose_name='Статус оффера')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлен')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Ответил в')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает в')),
                ('courier', models.ForeignKey(limit_choices_to={'user_type': 'courier'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_offers', to=settings.AUTH_USER_MODEL, verbose_name='Курьер')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='delivery.delivery', verbose_name='Доставка')),
            ],
            options={
                'verbose_name': 'Диспетчерская',
                'verbose_name_plural': 'Диспетчерская',
            },
        ),
        migrations.AddIndex(
            model_name='courierslot',
            index=models.Index(fields=['start_at', 'end_at'], name='delivery_co_start_a_179913_idx'),
        ),
        migrations.AddIndex(
            model_name='courierslot',
            index=models.Index(fields=['courier', 'start_at'], name='delivery_co_courier_284cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryoffer',
            index=models.Index(fields=['delivery', 'courier'], name='delivery_de_deliver_bd459a_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryoffer',
            index=models.Index(fields=['status', 'expires_at'], name='delivery_de_status_598725_idx'),
        ),
    ]
