# Generated by Django 6.0.2 on 2026-02-16 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('pending', 'Ожидание курьера'), ('assigned', 'Назначен курьер'), ('picked_up', 'Заказ забран'), ('delivered', 'Доставлено'), ('canceled', 'Отменено')], default='pending', max_length=50, verbose_name='Статус доставки')),
                ('pickup_at', models.DateTimeField(blank=True, null=True, verbose_name='Время забора')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Время доставки')),
                ('time_left', models.IntegerField(default=0, verbose_name='Осталось времени')),
                ('deadline_at', models.CharField(max_length=255, verbose_name='Доставить до')),
                ('client_comment', models.TextField(blank=True, default='', verbose_name='Комментарий клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(blank=True, limit_choices_to={'role': 'courier'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Курьер')),
                ('point_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries_from', to='main.address')),
                ('point_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries_to', to='main.address')),
            ],
        ),
    ]
