# Generated by Django 5.2.12 on 2026-03-24 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('main', '0003_darkstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierslot',
            name='darkstore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.darkstore', verbose_name='Даркстор'),
        ),
    ]
