# Generated by Django 5.2.12 on 2026-03-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_courierslot_darkstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('searching_courier', 'Поиск курьера'), ('courier_assigned', 'Курьер назначен'), ('courier_arrived', 'Курьер прибыл'), ('picked_up', 'Забрал посылку'), ('in_delivery', 'В пути'), ('delivered', 'Доставлено'), ('canceled', 'Отменено'), ('courier_arrived_b', 'Курьер прибыл в точку назначения'), ('waiting_pickup', 'Бесплатное ожидание'), ('canceled_by_client', 'Отменено клиентом')], default='pending', max_length=50, verbose_name='Статус доставки'),
        ),
    ]
