# Generated by Django 6.0.2 on 2026-02-16 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_delivery_options_alter_delivery_courier'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='deadline_at',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставить до'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='point_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries_from', to='main.address'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='point_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries_to', to='main.address'),
        ),
    ]
