# Generated by Django 5.2.12 on 2026-03-28 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_delivery_delivery_status'),
        ('main', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='courier_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='extra_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='delivery',
            name='extra_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='fact_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='fact_duration_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='planned_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='planned_duration_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='main.deliverytariff'),
        ),
    ]
