# Generated by Django 6.0.2 on 2026-02-17 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_delivery_deadline_at_alter_delivery_point_a_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='type_delivery',
            field=models.CharField(blank=True, choices=[('express', 'Экспресс'), ('standard', 'Стандарт')], max_length=50, null=True, verbose_name='Тип доставки'),
        ),
        migrations.CreateModel(
            name='CourierSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Начало слота')),
                ('end_at', models.DateTimeField(verbose_name='Конец слота')),
                ('status', models.CharField(choices=[('in_work', 'в работе'), ('offered', 'предложен'), ('planned', 'запланирован'), ('closed_early', 'закрыт досрочно'), ('paid_break', 'оплачиваемая пауза'), ('unpaid_break', 'неоплачиваемая пауза'), ('no_show', 'невыход')], db_index=True, default='planned', max_length=20, verbose_name='Статус слота')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'courier'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booked_slots', to=settings.AUTH_USER_MODEL, verbose_name='Занят курьером')),
                ('reserved_for', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'courier'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserved_slots', to=settings.AUTH_USER_MODEL, verbose_name='Зарезервирован для курьера')),
            ],
            options={
                'verbose_name': 'Слот курьера',
                'verbose_name_plural': 'Слоты курьеров',
                'ordering': ['-start_at'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.courierslot', verbose_name='Слот'),
        ),
        migrations.AddIndex(
            model_name='courierslot',
            index=models.Index(fields=['start_at', 'end_at'], name='delivery_co_start_a_179913_idx'),
        ),
        migrations.AddIndex(
            model_name='courierslot',
            index=models.Index(fields=['reserved_for', 'start_at'], name='delivery_co_reserve_455933_idx'),
        ),
        migrations.AddIndex(
            model_name='courierslot',
            index=models.Index(fields=['booked_by', 'start_at'], name='delivery_co_booked__b852fc_idx'),
        ),
    ]
