# Generated by Django 6.0.2 on 2026-02-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delivery_price_delivery_type_delivery_courierslot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доставить до'),
        ),
    ]
