# Generated by Django 5.2.12 on 2026-03-29 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delivery_commission_amount_delivery_courier_earnings_and_more'),
        ('main', '0007_deliveryzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='darkstore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='main.darkstore', verbose_name='Даркстор'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='main.deliveryzone', verbose_name='Зона'),
        ),
    ]
