# Generated by Django 5.2.12 on 2026-03-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_delivery_darkstore_delivery_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличка'), ('mbank', 'MBank')], default='cash', max_length=20, verbose_name='Оплата'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачено'), ('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('failed', 'Ошибка оплаты'), ('canceled', 'Отменено')], default='unpaid', max_length=20, verbose_name='Статус оплаты'),
        ),
    ]
