# Generated by Django 5.2.12 on 2026-03-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_delivery_payment_method_delivery_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='type_transport',
            field=models.CharField(choices=[('foot', 'Пеший'), ('bike', 'Велосипед'), ('moped', 'Мопед'), ('car', 'Машина')], default='standard', max_length=20, verbose_name='Тип транспорта'),
        ),
    ]
