# Generated by Django 5.2.12 on 2026-04-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_delivery_type_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierslot',
            name='slot_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
