# Generated by Django 5.2.12 on 2026-04-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_courierslot_slot_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='cancel_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина отмены'),
        ),
    ]
