# Generated by Django 5.2.12 on 2026-04-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_delivery_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='canceled_by',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Кем отменено'),
        ),
    ]
