# Generated by Django 5.2.12 on 2026-04-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_delivery_canceled_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='canceled_by',
        ),
    ]
