# Generated by Django 5.2.12 on 2026-04-09 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_remove_delivery_canceled_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('completed', 'completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.OneToOneField(limit_choices_to={'user_type': 'courier'}, on_delete=django.db.models.deletion.CASCADE, related_name='active_route', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourierRouteStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('pickup', 'pickup'), ('dropoff', 'dropoff')], max_length=10)),
                ('sequence', models.PositiveIntegerField(db_index=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('arrived', 'arrived'), ('done', 'done'), ('skipped', 'skipped')], default='pending', max_length=20)),
                ('eta_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='delivery.delivery')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='delivery.courierroute')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['route', 'sequence'], name='delivery_co_route_i_54a096_idx'), models.Index(fields=['delivery', 'stop_type'], name='delivery_co_deliver_2ddf9c_idx')],
            },
        ),
    ]
