# Generated by Django 5.2.12 on 2026-04-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_courierroute_courierroutestop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courierroute',
            options={'verbose_name': 'Маршрут курьера', 'verbose_name_plural': 'Маршруты курьеров'},
        ),
        migrations.AlterModelOptions(
            name='courierroutestop',
            options={'ordering': ['sequence'], 'verbose_name': 'Остановка маршрута', 'verbose_name_plural': 'Остановки маршрута'},
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_hidden_for_client',
            field=models.BooleanField(default=False),
        ),
    ]
