# Generated by Django 5.2.12 on 2026-05-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_alter_courierroute_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта')], default='cash', max_length=20, verbose_name='Оплата'),
        ),
    ]
