# Generated by Django 5.2.12 on 2026-05-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_delivery_waiting_minutes_delivery_waiting_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='waiting_minutes',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='waiting_price',
        ),
    ]
