# Generated by Django 5.2.12 on 2026-05-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_remove_delivery_waiting_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='waiting_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Платное ожидание (мин)'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='waiting_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость ожидания'),
        ),
    ]
