# Generated by Django 5.2.12 on 2026-05-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_delivery_waiting_minutes_delivery_waiting_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='free_waiting_minutes',
        ),
        migrations.AddField(
            model_name='delivery',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая цена'),
        ),
    ]
