# Generated by Django 6.0.2 on 2026-02-16 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('express', 'Экспресс'), ('standard', 'Стандарт')], max_length=50, verbose_name='Тип заказа')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('assembler', models.CharField(max_length=255, verbose_name='Сборщик')),
                ('courier_name', models.CharField(max_length=255, verbose_name='Имя курьера')),
                ('order_status', models.CharField(default='created', max_length=50, verbose_name='Статус заказа')),
                ('time_left', models.IntegerField(default=0, verbose_name='Осталось времени')),
                ('delivered_to', models.CharField(max_length=255, verbose_name='Доставить до')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
