# Generated by Django 5.2.12 on 2026-03-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('express', 'Экспресс'), ('standard', 'Стандарт')], max_length=50, verbose_name='Тип заказа')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('assembler', models.CharField(max_length=255, verbose_name='Сборщик')),
                ('courier_name', models.CharField(max_length=255, verbose_name='Имя курьера')),
                ('order_status', models.CharField(choices=[('created', 'CTE'), ('processing', 'Ожидание выдачи'), ('ready', 'Pick Up'), ('shipped', 'Курьер в пути')], default='created', max_length=50, verbose_name='Статус заказа')),
                ('time_left', models.IntegerField(default=0, verbose_name='Осталось времени')),
                ('delivered_to', models.CharField(max_length=255, verbose_name='Доставить до')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
