# Generated by Django 6.0.2 on 2026-02-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('created', 'CTE'), ('processing', 'Ожидание выдачи'), ('ready', 'Pick Up'), ('shipped', 'Курьер в пути')], default='created', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
