# Generated by Django 5.2.12 on 2026-03-31 06:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0006_delivery_payment_method_delivery_payment_status'),
        ('taxi', '0003_alter_taxiride_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(default='mbank', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='payments/qr/')),
                ('deeplink', models.URLField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mkassa', 'MKassa')], default='mkassa', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличка'), ('mbank', 'MBank')], default='mbank', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('paid', 'Оплачено'), ('failed', 'Ошибка'), ('canceled', 'Отменено')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='KGS', max_length=10)),
                ('external_payment_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('qr_url', models.URLField(blank=True, null=True)),
                ('deeplink', models.TextField(blank=True, null=True)),
                ('raw_init_response', models.JSONField(blank=True, null=True)),
                ('raw_check_response', models.JSONField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='delivery.delivery')),
                ('taxi_ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='taxi.taxiride')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено'), ('paid', 'Выплачено'), ('canceled', 'Отменено')], default='pending', max_length=16)),
                ('note', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='balance.workerwallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('order_earning', 'Доход по заказу'), ('withdrawal_hold', 'Холд на вывод'), ('withdrawal', 'Вывод'), ('withdrawal_cancel', 'Отмена вывода'), ('adjustment', 'Корректировка')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('completed', 'Выполнено'), ('canceled', 'Отменено')], default='completed', max_length=16)),
                ('channel', models.CharField(blank=True, choices=[('cash', 'Наличка'), ('mbank', 'MBank')], max_length=16, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sign', models.SmallIntegerField(default=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='delivery.delivery')),
                ('taxi_ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='taxi.taxiride')),
                ('withdrawal_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='balance.withdrawalrequest')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='balance.workerwallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['wallet', 'status', 'created_at'], name='balance_wal_wallet__f2f7da_idx'), models.Index(fields=['wallet', 'channel', 'created_at'], name='balance_wal_wallet__9b5ccf_idx'), models.Index(fields=['transaction_type', 'status'], name='balance_wal_transac_085bf2_idx')],
            },
        ),
    ]
