# Generated by Django 5.2.12 on 2026-04-04 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'verbose_name': 'Транзакция кошелька', 'verbose_name_plural': 'Транзакции кошельков'},
        ),
        migrations.AlterModelOptions(
            name='workerwallet',
            options={'verbose_name': 'Кошелек работника', 'verbose_name_plural': 'Кошельки работников'},
        ),
        migrations.RemoveIndex(
            model_name='wallettransaction',
            name='balance_wal_wallet__f2f7da_idx',
        ),
        migrations.RemoveIndex(
            model_name='wallettransaction',
            name='balance_wal_wallet__9b5ccf_idx',
        ),
        migrations.RemoveIndex(
            model_name='wallettransaction',
            name='balance_wal_transac_085bf2_idx',
        ),
        migrations.AddIndex(
            model_name='workerwallet',
            index=models.Index(fields=['worker'], name='balance_wor_worker__156e16_idx'),
        ),
    ]
