# Generated by Django 5.2.12 on 2026-05-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_withdrawalrequest_card_holder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Заявка на вывод средств', 'verbose_name_plural': 'Заявка на вывод средств'},
        ),
    ]
