# Generated by Django 5.2.12 on 2026-05-08 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_alter_withdrawalrequest_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('required_orders', models.PositiveIntegerField(default=0)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Бонусная миссия',
                'verbose_name_plural': 'Бонусные миссии',
            },
        ),
        migrations.CreateModel(
            name='BonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bonus_type', models.CharField(choices=[('orders_count', 'За количество заказов'), ('online_hours', 'За онлайн время'), ('peak_hours', 'Часы пик'), ('rating', 'Высокий рейтинг'), ('mission', 'Миссия'), ('newbie', 'Новичок')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('required_orders', models.PositiveIntegerField(default=0)),
                ('required_online_hours', models.PositiveIntegerField(default=0)),
                ('required_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reward_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Правило бонуса',
                'verbose_name_plural': 'Правила бонусов',
            },
        ),
        migrations.CreateModel(
            name='BonusReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_type', models.CharField(choices=[('orders_count', 'За количество заказов'), ('online_hours', 'За онлайн время'), ('peak_hours', 'Часы пик'), ('rating', 'Высокий рейтинг'), ('mission', 'Миссия'), ('newbie', 'Новичок')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_canceled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='balance.bonusmission')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_rewards', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='balance.bonusrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerMissionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_orders', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('rewarded', models.BooleanField(default=False)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='balance.bonusmission')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('worker', 'mission')},
            },
        ),
    ]
