# Generated by Django 5.2.12 on 2026-05-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0005_bonusmission_bonusrule_bonusreward_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusreward',
            options={'ordering': ['-created_at'], 'verbose_name': 'Бонусные награды', 'verbose_name_plural': 'Бонусные награды'},
        ),
        migrations.AlterModelOptions(
            name='workermissionprogress',
            options={'verbose_name': 'Бонусные прогрессы', 'verbose_name_plural': 'Бонусные прогрессы'},
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('order_earning', 'Доход по заказу'), ('withdrawal_hold', 'Холд на вывод'), ('withdrawal', 'Вывод'), ('withdrawal_cancel', 'Отмена вывода'), ('adjustment', 'Корректировка'), ('bonus', 'Бонус')], max_length=32),
        ),
    ]
