# Generated by Django 5.2.12 on 2026-05-19 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0006_alter_bonusreward_options_and_more'),
        ('payments', '0006_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('order_earning_online', 'Доход по онлайн заказу'), ('order_earning_cash', 'Доход по наличному заказу'), ('order_earning', 'Доход по заказу'), ('withdrawal_hold', 'Холд на вывод'), ('withdrawal', 'Вывод'), ('withdrawal_cancel', 'Отмена вывода'), ('adjustment', 'Корректировка'), ('bonus', 'Бонус')], max_length=32),
        ),
    ]
