# Generated by Django 5.2.12 on 2026-05-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0007_wallettransaction_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusrule',
            name='required_reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('order_earning_cash', 'Доход наличными'), ('order_earning_online', 'Доход онлайн'), ('deposit', 'Пополнение'), ('withdrawal_hold', 'Холд на вывод'), ('withdrawal', 'Вывод'), ('withdrawal_cancel', 'Отмена вывода'), ('adjustment', 'Корректировка'), ('bonus', 'Бонус')], max_length=32),
        ),
    ]
