# Generated by Django 5.2.12 on 2026-05-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0008_bonusrule_required_reviews_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Заявка на вывод средств', 'verbose_name_plural': 'Заявки на вывод средств'},
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='channel',
            field=models.CharField(blank=True, choices=[('cash', 'Наличка'), ('online', 'Онлайн')], max_length=16, null=True),
        ),
    ]
