# Generated by Django 5.2.12 on 2026-05-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0009_alter_withdrawalrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('canceled', 'Отменено')], default='pending', max_length=16),
        ),
    ]
