# Generated by Django 5.2.12 on 2026-05-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0010_alter_withdrawalrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantpaymentaccount',
            name='provider',
            field=models.CharField(default='online', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличка'), ('online', 'Онлайн')], default='online', max_length=20),
        ),
    ]
