# Generated by Django 5.2.12 on 2026-05-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0011_alter_merchantpaymentaccount_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('order_earning_cash', 'Доход наличными'), ('order_earning_online', 'Доход онлайн'), ('deposit', 'Пополнение'), ('cash_commission', 'Вычет комиссии'), ('withdrawal_hold', 'Холд на вывод'), ('withdrawal', 'Вывод'), ('withdrawal_cancel', 'Отмена вывода'), ('adjustment', 'Корректировка'), ('bonus', 'Бонус')], max_length=32),
        ),
    ]
