# Generated by Django 5.2.12 on 2026-04-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_external_id_payment_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
