# Generated by Django 5.2.12 on 2026-05-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type_payment',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
