# Generated by Django 5.2.12 on 2026-05-23 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0012_alter_wallettransaction_transaction_type'),
        ('payments', '0006_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NambaTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='balance.wallettransaction')),
            ],
        ),
    ]
