# Generated by Django 5.2.12 on 2026-03-24 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('user_type', models.CharField(blank=True, choices=[('client', 'Клиент'), ('courier', 'Курьер'), ('driver', 'Водитель'), ('admin', 'Администратор'), ('operator', 'Оператор')], default='client', max_length=20, verbose_name='Тип пользователя')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('home_address', models.CharField(blank=True, max_length=255, null=True)),
                ('work_address', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Код подтверждения')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='CourierProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('foot', 'Пеший'), ('bike', 'Велосипед'), ('moped', 'Мопед'), ('car', 'Машина')], max_length=20)),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='couriers/selfie/')),
                ('passport_front', models.ImageField(blank=True, null=True, upload_to='couriers/passport/front/')),
                ('passport_back', models.ImageField(blank=True, null=True, upload_to='couriers/passport/back/')),
                ('car_brand', models.CharField(blank=True, max_length=100)),
                ('car_model', models.CharField(blank=True, max_length=100)),
                ('car_color', models.CharField(blank=True, max_length=50)),
                ('car_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'courier'}, on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Курьер',
                'verbose_name_plural': 'Курьеры',
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='drivers/selfie/', verbose_name='Селфи')),
                ('passport_front', models.ImageField(blank=True, null=True, upload_to='drivers/passport/front/', verbose_name='Паспорт лицевая сторона')),
                ('passport_back', models.ImageField(blank=True, null=True, upload_to='drivers/passport/back/', verbose_name='Паспорт обратная сторона')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='Номер паспорта')),
                ('seria_and_number', models.CharField(blank=True, max_length=50, verbose_name='Серия и номер водительского права')),
                ('date_of_issue', models.DateField(blank=True, null=True, verbose_name='Дата выдачи водительского права')),
                ('issuing_authority', models.CharField(blank=True, max_length=255, verbose_name='Орган, выдавший водительское право')),
                ('driver_license_front', models.ImageField(blank=True, null=True, upload_to='drivers/license/front/', verbose_name='Права лицевая сторона')),
                ('driver_license_back', models.ImageField(blank=True, null=True, upload_to='drivers/license/back/', verbose_name='Права обратная сторона')),
                ('car_brand', models.CharField(blank=True, max_length=100, verbose_name='Марка машины')),
                ('car_model', models.CharField(blank=True, max_length=100, verbose_name='Модель машины')),
                ('car_color', models.CharField(blank=True, max_length=50, verbose_name='Цвет машины')),
                ('car_number', models.CharField(blank=True, max_length=20, verbose_name='Номер машины')),
                ('car_type', models.CharField(blank=True, max_length=50, verbose_name='Тип машины')),
                ('car_photo', models.ImageField(blank=True, null=True, upload_to='drivers/car/', verbose_name='Фото машины')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Таксист',
                'verbose_name_plural': 'Таксисты',
            },
        ),
        migrations.CreateModel(
            name='WorkerLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Местоположение водителей/курьеров',
                'verbose_name_plural': 'Местоположение водителей/курьеров',
            },
        ),
        migrations.CreateModel(
            name='WorkerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('is_busy', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cтатусы водителей/курьеров',
                'verbose_name_plural': 'Cтатусы водителей/курьеров',
            },
        ),
    ]
