# Generated by Django 6.0.2 on 2026-02-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('client', 'Клиент'), ('courier', 'Курьер'), ('driver', 'Водитель'), ('admin', 'Администратор'), ('operator', 'Оператор')], max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
