# Generated by Django 5.2.12 on 2026-03-24 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_darkstore'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprofile',
            name='darkstore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers', to='main.darkstore', verbose_name='Даркстор'),
        ),
    ]
