# Generated by Django 5.2.12 on 2026-03-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_courierprofile_darkstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierDispatch',
            fields=[
            ],
            options={
                'verbose_name': 'Диспетчерская курьеров',
                'verbose_name_plural': 'Диспетчерская курьеров',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='DriverDispatch',
            fields=[
            ],
            options={
                'verbose_name': 'Диспетчерская таксистов',
                'verbose_name_plural': 'Диспетчерская таксистов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
