# Generated by Django 6.0.2 on 2026-02-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_admin_client_courier_driver_operator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
