# Generated by Django 5.2.12 on 2026-03-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_courierdispatch_driverdispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Средний рейтинг'),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество отзывов'),
        ),
    ]
