# Generated by Django 5.2.12 on 2026-03-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_rating_avg_user_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprofile',
            name='driver_license_back',
            field=models.ImageField(blank=True, null=True, upload_to='couriers/license/back/', verbose_name='Права обратная сторона'),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='driver_license_front',
            field=models.ImageField(blank=True, null=True, upload_to='couriers/license/front/', verbose_name='Права лицевая сторона'),
        ),
    ]
