# Generated by Django 5.2.12 on 2026-03-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_courierprofile_driver_license_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orders_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество заказов'),
        ),
    ]
