# Generated by Django 5.2.12 on 2026-03-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_orders_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orders_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество заказов'),
        ),
    ]
