# Generated by Django 5.2.12 on 2026-03-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_tariff_unique_together_remove_tariff_city'),
        ('users', '0007_alter_user_orders_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprofile',
            name='delivery_zones',
            field=models.ManyToManyField(blank=True, related_name='courier_profiles', to='main.deliveryzone', verbose_name='Разрешенные зоны доставки'),
        ),
    ]
