# Generated by Django 5.2.12 on 2026-03-30 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_tariff_unique_together_remove_tariff_city'),
        ('users', '0008_courierprofile_delivery_zones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierprofile',
            name='delivery_zones',
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='delivery_zones',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courier_profiles', to='main.deliveryzone', verbose_name='Разрешенные зоны доставки'),
            preserve_default=False,
        ),
    ]
