# Generated by Django 5.2.12 on 2026-03-30 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_tariff_unique_together_remove_tariff_city'),
        ('users', '0009_remove_courierprofile_delivery_zones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierprofile',
            name='delivery_zones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_profiles', to='main.deliveryzone', verbose_name='Разрешенные зоны доставки'),
        ),
    ]
