# Generated by Django 5.2.12 on 2026-04-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_courierprofile_delivery_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerstatus',
            name='active_deliveries_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerstatus',
            name='max_parallel_deliveries',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
