# Generated by Django 5.2.12 on 2026-04-17 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_home_address_remove_user_work_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='intercom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Дом, Работа, Универ', max_length=100, verbose_name='Название адреса')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('entrance', models.CharField(blank=True, max_length=20, verbose_name='Подъезд')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='Этаж')),
                ('apartment', models.CharField(blank=True, max_length=50, verbose_name='Квартира / офис')),
                ('intercom', models.CharField(blank=True, max_length=50, verbose_name='Домофон')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес пользователя',
                'verbose_name_plural': 'Адреса пользователей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_usera_user_id_ba6066_idx')],
            },
        ),
    ]
