# Generated by Django 5.2.12 on 2026-04-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_address_remove_user_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Логотип'),
        ),
    ]
