# Generated by Django 5.2.12 on 2026-05-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='universal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Универсальный код'),
        ),
    ]
