# Generated by Django 5.2.12 on 2026-05-07 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_universal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverCarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='drivers/car/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='users.driverprofile')),
            ],
        ),
    ]
