# Generated by Django 5.2.12 on 2026-05-07 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_drivercarimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='car_photo',
        ),
        migrations.CreateModel(
            name='CourierCarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='couriers/equipment/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_images', to='users.courierprofile', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Фото курьера',
                'verbose_name_plural': 'Фото курьера',
            },
        ),
    ]
