# Generated by Django 5.2.12 on 2026-05-08 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_driverprofile_car_photo_couriercarimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couriercarimage',
            options={},
        ),
        migrations.AlterField(
            model_name='couriercarimage',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_images', to='users.courierprofile'),
        ),
        migrations.AlterField(
            model_name='couriercarimage',
            name='image',
            field=models.ImageField(upload_to='couriers/equipment/'),
        ),
        migrations.AlterField(
            model_name='courierprofile',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('foot', 'Пеший'), ('bike', 'Велосипед'), ('moped', 'Мопед'), ('car', 'Машина')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20),
        ),
    ]
