# Generated by Django 5.2.12 on 2026-05-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_couriercarimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], max_length=20),
        ),
    ]
