# Generated by Django 5.2.12 on 2026-05-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_courierprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprofile',
            name='last_car_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='last_car_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courierprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20),
        ),
    ]
