# Generated by Django 5.2.12 on 2026-05-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_driverprofile_car_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='car_photo',
        ),
    ]
