# Generated by Django 5.2.12 on 2026-05-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_driverprofile_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='car_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
