# Generated by Django 5.2.12 on 2026-05-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_driverprofile_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprofile',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='couriers/car/', verbose_name='Фото машины'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/car/', verbose_name='Фото машины'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус проверки'),
        ),
    ]
