# Generated by Django 5.2.12 on 2026-05-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_courierprofile_car_image_driverprofile_car_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerstatus',
            name='online_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerstatus',
            name='today_online_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
