# Generated by Django 5.2.12 on 2026-05-21 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_deliverytariff_door_to_door_price_and_more'),
        ('users', '0027_workerstatus_online_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='darkstore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='main.darkstore', verbose_name='Даркстор'),
        ),
    ]
