# Generated by Django 5.2.12 on 2026-03-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('car_class', models.CharField(choices=[('econom', 'Эконом'), ('comfort', 'Комфорт'), ('comfort_plus', 'Комфорт+'), ('business', 'Бизнес')], max_length=20, verbose_name='Класс автомобиля')),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая плата')),
                ('included_km', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Включенные километры')),
                ('included_min', models.PositiveIntegerField(default=0, verbose_name='Включенные минуты')),
                ('per_km_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Тариф за километр')),
                ('per_min_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Тариф за минуту')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Процент комиссии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
