# Generated by Django 5.2.12 on 2026-03-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterUniqueTogether(
            name='tariff',
            unique_together={('city', 'car_class')},
        ),
    ]
