# Generated by Django 5.2.12 on 2026-03-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_darkstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_deliveru', models.CharField(choices=[('foot', 'Пеший'), ('bike', 'Велосипед'), ('moped', 'Мопед'), ('car', 'Машина')], max_length=20, verbose_name='Тип доставки')),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая плата')),
                ('included_km', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Включенные километры')),
                ('included_min', models.PositiveIntegerField(default=0, verbose_name='Включенные минуты')),
                ('per_km_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Тариф за километр')),
                ('per_min_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Тариф за минуту')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Процент комиссии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тариф доставки',
                'verbose_name_plural': 'Тарифы доставки',
            },
        ),
    ]
