# Generated by Django 5.2.12 on 2026-03-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_deliverytariff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverytariff',
            old_name='type_deliveru',
            new_name='type_delivery',
        ),
    ]
