# Generated by Django 5.2.12 on 2026-03-28 09:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_delivery_delivery_status'),
        ('main', '0005_rename_type_deliveru_deliverytariff_type_delivery'),
        ('taxi', '0002_alter_taxiride_order_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='delivery.delivery')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='taxi.taxiride')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('delivery__isnull', False), ('ride__isnull', True)), models.Q(('delivery__isnull', True), ('ride__isnull', False)), _connector='OR'), name='review_has_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('delivery__isnull', False)), fields=('from_user', 'to_user', 'delivery'), name='unique_delivery_review_pair'), models.UniqueConstraint(condition=models.Q(('ride__isnull', False)), fields=('from_user', 'to_user', 'ride'), name='unique_ride_review_pair')],
            },
        ),
    ]
