# Generated by Django 5.2.12 on 2026-03-29 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зоны')),
                ('min_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Мин. широта')),
                ('max_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Макс. широта')),
                ('min_lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Мин. долгота')),
                ('max_lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Макс. долгота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('darkstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='main.darkstore', verbose_name='Даркстор')),
            ],
            options={
                'verbose_name': 'Зона доставки',
                'verbose_name_plural': 'Зоны доставки',
            },
        ),
    ]
