# Generated by Django 5.2.12 on 2026-03-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_deliveryzone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryzone',
            name='max_lat',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='max_lon',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='min_lat',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='min_lon',
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='polygon',
            field=models.JSONField(blank=True, default=list, verbose_name='Координаты полигона'),
        ),
    ]
