# Generated by Django 5.2.12 on 2026-03-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_deliveryzone_max_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darkstore',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='darkstore',
            name='lon',
        ),
    ]
