# Generated by Django 5.2.12 on 2026-03-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_darkstore_lat_remove_darkstore_lon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tariff',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='city',
        ),
    ]
