# Generated by Django 5.2.12 on 2026-03-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_tariff_unique_together_remove_tariff_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytariff',
            name='door_to_door_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена до двери'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverytariff',
            name='entrance_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена до подьезда'),
            preserve_default=False,
        ),
    ]
