# Generated by Django 5.2.12 on 2026-05-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_deliverytariff_door_to_door_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytariff',
            name='waiting_per_minute',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена ожидания за минуту'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='waiting_per_minute',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена ожидания за минуту'),
        ),
    ]
