# Generated by Django 5.2.12 on 2026-05-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_deliverytariff_waiting_per_minute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytariff',
            name='waiting_free_min',
            field=models.PositiveIntegerField(default=5, verbose_name='Бесплатное ожидание (мин)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='waiting_free_min',
            field=models.PositiveIntegerField(default=5, verbose_name='Бесплатное ожидание (мин)'),
        ),
    ]
