# Generated by Django 5.2.12 on 2026-05-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_deliverytariff_waiting_free_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytariff',
            name='minimum_balance',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Минимальный баланс'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='minimum_balance',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Минимальный баланс'),
        ),
    ]
