# Generated by Django 5.2.12 on 2026-05-23 13:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_deliverytariff_minimum_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='car_class',
            field=models.CharField(choices=[('econom', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес'), ('van', 'Минивэн')], max_length=20, verbose_name='Класс автомобиля'),
        ),
        migrations.CreateModel(
            name='DeliveryCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('type_delivery', models.CharField(choices=[('express', 'Экспресс'), ('standard', 'Стандарт')], db_index=True, max_length=20, verbose_name='Тип доставки')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Карта')], help_text='Если пусто — применяется ко всем типам оплат', max_length=20, null=True, verbose_name='Тип оплаты')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5, verbose_name='Процент комиссии')),
                ('min_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Минимальная комиссия')),
                ('max_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная комиссия')),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=Decimal('300.00'), max_digits=10, verbose_name='Минимальный баланс для работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Комиссия доставки',
                'verbose_name_plural': 'Комиссии доставки',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['type_delivery', 'payment_method'], name='main_delive_type_de_d4cca4_idx'), models.Index(fields=['is_active'], name='main_delive_is_acti_bc8873_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxiCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('car_class', models.CharField(choices=[('econom', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес'), ('van', 'Минивэн')], db_index=True, max_length=20, verbose_name='Класс автомобиля')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Карта')], help_text='Если пусто — применяется ко всем типам оплат', max_length=20, null=True, verbose_name='Тип оплаты')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Процент комиссии')),
                ('min_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Минимальная комиссия')),
                ('max_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная комиссия')),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=Decimal('300.00'), help_text='Если баланс ниже — водитель не сможет принимать заказы', max_digits=10, verbose_name='Минимальный баланс для работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Комиссия такси',
                'verbose_name_plural': 'Комиссии такси',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['car_class', 'payment_method'], name='main_taxico_car_cla_3586fd_idx'), models.Index(fields=['is_active'], name='main_taxico_is_acti_93845d_idx')],
            },
        ),
    ]
