# Generated by Django 5.2.12 on 2026-05-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_tariff_car_class_deliverycommission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytariff',
            name='commission_percent',
        ),
        migrations.RemoveField(
            model_name='deliverytariff',
            name='minimum_balance',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='commission_percent',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='minimum_balance',
        ),
    ]
