# Generated by Django 5.2.12 on 2026-03-21 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_a', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес откуда')),
                ('point_b', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес куда')),
                ('pickup_lat', models.FloatField(blank=True, null=True, verbose_name='Широта точки А')),
                ('pickup_lon', models.FloatField(blank=True, null=True, verbose_name='Долгота точки А')),
                ('dropoff_lat', models.FloatField(blank=True, null=True, verbose_name='Широта точки Б')),
                ('dropoff_lon', models.FloatField(blank=True, null=True, verbose_name='Долгота точки Б')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('assigned', 'Назначен водитель'), ('accepted', 'Водитель принял'), ('arrived', 'Водитель приехал'), ('in_trip', 'В поездке'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('failed', 'Не удалось')], default='searching_driver', max_length=20, verbose_name='Статус')),
                ('car_class', models.CharField(choices=[('econom', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес'), ('van', 'Минивэн')], default='econom', max_length=20, verbose_name='Класс')),
                ('passengers', models.PositiveSmallIntegerField(default=1, verbose_name='Пассажиры')),
                ('client_comment', models.TextField(blank=True, default='', verbose_name='Комментарий клиента')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Дистанция (км)')),
                ('duration_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время (мин)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('base_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_km_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_min_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('included_km', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('included_min', models.PositiveIntegerField(default=0)),
                ('commission_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver_payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта')], default='cash', max_length=20, verbose_name='Оплата')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачено'), ('paid', 'Оплачено'), ('refunded', 'Возврат')], default='unpaid', max_length=20, verbose_name='Статус оплаты')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Назначен')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Принят')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='Прибыл')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начал поездку')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершил')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменено')),
                ('order_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('canceled_by', models.CharField(blank=True, choices=[('client', 'Клиент'), ('driver', 'Водитель'), ('system', 'Система'), ('operator', 'Оператор')], max_length=20, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='taxi_rides', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'driver'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_rides', to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
            },
        ),
        migrations.CreateModel(
            name='TaxiOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принят'), ('rejected', 'Отклонен'), ('expired', 'Истек')], default='pending', max_length=20, verbose_name='Статус оффера')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлен')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Ответил в')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает в')),
                ('driver', models.ForeignKey(limit_choices_to={'user_type': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='taxi_offers', to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='taxi.taxiride', verbose_name='Поездка')),
            ],
            options={
                'verbose_name': 'Оффер водителю',
                'verbose_name_plural': 'Офферы водителям',
                'indexes': [models.Index(fields=['ride', 'driver'], name='taxi_taxiof_ride_id_8cc1e5_idx'), models.Index(fields=['status', 'expires_at'], name='taxi_taxiof_status_99a35b_idx')],
            },
        ),
    ]
