# Generated by Django 6.0.2 on 2026-02-16 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('assigned', 'Назначен водитель'), ('accepted', 'Водитель принял'), ('arrived', 'Водитель приехал'), ('in_trip', 'В поездке'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('failed', 'Не удалось')], default='pending', max_length=20, verbose_name='Статус')),
                ('car_class', models.CharField(choices=[('econom', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес'), ('van', 'Минивэн')], default='econom', max_length=20, verbose_name='Класс')),
                ('passengers', models.PositiveSmallIntegerField(default=1, verbose_name='Пассажиры')),
                ('client_comment', models.TextField(blank=True, default='', verbose_name='Комментарий клиента')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Дистанция (км)')),
                ('duration_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время (мин)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта')], default='cash', max_length=20, verbose_name='Оплата')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачено'), ('paid', 'Оплачено'), ('refunded', 'Возврат')], default='unpaid', max_length=20, verbose_name='Статус оплаты')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Назначен')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Принят')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='Прибыл')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начал поездку')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершил')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменено')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='taxi_rides', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_rides', to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
                ('point_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxi_from', to='main.address')),
                ('point_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxi_to', to='main.address')),
            ],
        ),
    ]
