# Generated by Django 5.2.12 on 2026-03-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxiride',
            name='order_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
