# Generated by Django 6.0.2 on 2026-02-16 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('taxi', '0002_alter_taxiride_client_alter_taxiride_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxiride',
            name='point_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taxi_from', to='main.address'),
        ),
        migrations.AlterField(
            model_name='taxiride',
            name='point_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taxi_to', to='main.address'),
        ),
    ]
