# Generated by Django 5.2.12 on 2026-04-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_taxiride_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiride',
            name='is_hidden_for_client',
            field=models.BooleanField(default=False),
        ),
    ]
