# Generated by Django 6.0.2 on 2026-02-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_taxiride_point_a_alter_taxiride_point_b'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxiride',
            options={'verbose_name': 'Поездка', 'verbose_name_plural': 'Поездки'},
        ),
    ]
