# Generated by Django 5.2.12 on 2026-05-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_alter_taxiride_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiride',
            name='waiting_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Платное ожидание (мин)'),
        ),
        migrations.AddField(
            model_name='taxiride',
            name='waiting_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость ожидания'),
        ),
        migrations.AlterField(
            model_name='taxiride',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачено'), ('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('failed', 'Ошибка оплаты'), ('canceled', 'Отменено'), ('refunded', 'Возврат')], default='unpaid', max_length=20, verbose_name='Статус оплаты'),
        ),
    ]
