# Generated by Django 5.2.12 on 2026-04-01 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0007_delivery_type_transport'),
        ('taxi', '0003_alter_taxiride_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=255, unique=True, verbose_name='OneSignal Player ID')),
                ('external_user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='OneSignal External User ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=20, verbose_name='Платформа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Push устройство',
                'verbose_name_plural': 'Push устройства',
                'indexes': [models.Index(fields=['user', 'is_active'], name='notify_push_user_id_69304a_idx'), models.Index(fields=['platform', 'is_active'], name='notify_push_platfor_c403e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('slot_remind_1h', 'За 1 час до начала слота'), ('slot_started', 'Слот начался'), ('slot_finished', 'Слот завершен'), ('delivery_offer_new', 'Курьеру пришел заказ'), ('delivery_courier_arrived', 'Курьер прибыл'), ('delivery_started', 'Доставка началась'), ('delivery_completed', 'Доставка завершена'), ('taxi_offer_new', 'Водителю пришел заказ'), ('taxi_driver_arrived', 'Водитель прибыл'), ('taxi_started', 'Поездка началась'), ('taxi_completed', 'Поездка завершена')], max_length=50, verbose_name='Тип события')),
                ('event_key', models.CharField(max_length=255, unique=True, verbose_name='Уникальный ключ события')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('canceled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Запланировано на')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ошибка в')),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID сообщения у провайдера')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Текст ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to='delivery.delivery', verbose_name='Доставка')),
                ('delivery_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to='delivery.deliveryoffer', verbose_name='Оффер доставки')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to='taxi.taxiride', verbose_name='Поездка')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to='delivery.courierslot', verbose_name='Слот')),
                ('taxi_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to='taxi.taxioffer', verbose_name='Оффер такси')),
            ],
            options={
                'verbose_name': 'Push уведомление',
                'verbose_name_plural': 'Push уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='notify_push_recipie_eed542_idx'), models.Index(fields=['event_type', 'status'], name='notify_push_event_t_bc7f8e_idx'), models.Index(fields=['scheduled_at', 'status'], name='notify_push_schedul_cc9112_idx'), models.Index(fields=['slot', 'event_type'], name='notify_push_slot_id_344928_idx'), models.Index(fields=['delivery', 'event_type'], name='notify_push_deliver_3dae5e_idx'), models.Index(fields=['ride', 'event_type'], name='notify_push_ride_id_d5fcba_idx')],
            },
        ),
    ]
