# Generated by Django 5.2.12 on 2026-04-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushdevice',
            old_name='player_id',
            new_name='onesignal_id',
        ),
    ]
