# Generated by Django 5.2.12 on 2026-04-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_rename_player_id_pushdevice_onesignal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushdevice',
            name='onesignal_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='OneSignal ID'),
        ),
    ]
